server:
  port: 8081
spring:
   redis:
     host: 127.0.0.1
     port: 6379
     password: ls140078
     jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: -1
      timeout: 5000
      database: 0
